#define MIN_NORMAL_TEMPERATURE 26
#define MAX_NORMAL_TEMPERATURE 29
#define MIN_NORMAL_AIR_MOISTURE 70
#define MAX_NORMAL_AIR_MOISTURE 80
#define MIN_NORMAL_SOIL_MOISTURE 45
#define MAX_NORMAL_SOIL_MOISTURE 60

#define MAX_EPOLL_REVENTS 5
#define BUF_LEN 1024